#!/bin/bash

set -o errexit

MSYS_NO_PATHCONV=1 subst /d a: | true && subst a: .

history -c
export HISTFILE=/a/local/.bash_history

export PATH=/a/script:$PATH
[[ -z $PROFILE ]] || export PATH=/a/script/profile/$PROFILE:$PATH

code /a --reuse-window
