#!/bin/bash

set -o errexit

git add --all
git commit --message "" --allow-empty-message

git push origin main || {
	git reset --soft HEAD~1
	git stash
	git pull
	git stash pop
	git add --all
	git commit --message "" --allow-empty-message
}
